version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: professional_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: professional_api
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3000:3000"
    networks:
      - app_network
    command: npm run start:prod

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
